import * as Tone from 'tone';
import {
  AUDIO_DEFAULT_ATTACK,
  AUDIO_DEFAULT_DECAY,
  AUDIO_DEFAULT_SUSTAIN,
  AUDIO_DEFAULT_RELEASE,
  AUDIO_DEFAULT_VOLUME,
  AUDIO_DEFAULT_CUTOFF,
} from './audioEngineConfig';

const RANGE_VOLUME_DB = { min: -60, max: 0, step: 1 };
const RANGE_TIME_ADR = { min: 0.01, max: 3.0, step: 0.01 };
const RANGE_MIX_WET = { min: 0.0, max: 1.0, step: 0.05 };
const RANGE_FILTER_HZ = { min: 20, max: 10000, step: 10 };

export const SOUND_PARAM_GROUPS = [
  { key: 'envelope', label: 'ENVELOPE:' },
  { key: 'filter', label: 'FILTER:' },
];

const ALL_ENGINES = ['monoSynth', 'membraneSynth', 'noiseSynth', 'metalSynth'];

export const SOUND_PARAMS = {
  attack: {
    min: 0.005,
    max: 2.0,
    step: 0.005,
    default: AUDIO_DEFAULT_ATTACK,
    label: 'ATTACK',
    group: 'envelope',
    supportedEngines: ALL_ENGINES,
  },
  decay: {
    ...RANGE_TIME_ADR,
    default: AUDIO_DEFAULT_DECAY,
    label: 'DECAY',
    group: 'envelope',
    supportedEngines: ALL_ENGINES,
  },
  sustain: {
    ...RANGE_MIX_WET,
    default: AUDIO_DEFAULT_SUSTAIN,
    label: 'SUSTAIN',
    group: 'envelope',
    supportedEngines: ['monoSynth'],
  },
  release: {
    ...RANGE_TIME_ADR,
    default: AUDIO_DEFAULT_RELEASE,
    label: 'RELEASE',
    group: 'envelope',
    supportedEngines: ['monoSynth', 'membraneSynth'],
  },
  volume: {
    ...RANGE_VOLUME_DB,
    default: AUDIO_DEFAULT_VOLUME,
    label: 'VOLUME',
    group: 'envelope',
    supportedEngines: ALL_ENGINES,
  },
  synthGlide: {
    min: 0.0,
    max: 0.5,
    step: 0.01,
    default: 0.0,
    label: 'GLIDE (GLIDE/PORTAMENTO)',
    group: 'envelope',
    supportedEngines: ['monoSynth'],
  },

  filterCutoff: {
    ...RANGE_FILTER_HZ,
    default: AUDIO_DEFAULT_CUTOFF,
    label: 'CUTOFF HZ',
    isEffect: true,
    nodeKey: 'fxFilter',
    targetParam: 'frequency',
    bypassValue: 10000,
    group: 'filter',
    supportedEngines: ALL_ENGINES,
  },
  filterQ: {
    min: 1.0,
    max: 15.0,
    step: 0.5,
    default: 1.0,
    label: 'RESONANCE (Q)',
    group: 'filter',
    targetParam: 'Q',
    supportedEngines: ALL_ENGINES,
  },
  filterEnvOctaves: {
    min: 0.0,
    max: 6.0,
    step: 0.5,
    default: 0.0,
    label: 'ENV MOD (OCTAVES)',
    group: 'filter',
    supportedEngines: ['monoSynth'],
  },

  bitcrusherWet: {
    ...RANGE_MIX_WET,
    default: 0.4,
    label: 'CRUSHER MIX',
    isEffect: true,
    nodeKey: 'fxBitcrusher',
    targetParam: 'wet',
    bypassValue: 0.0,
    group: 'crusher',
    supportedEngines: ALL_ENGINES,
  },
  bitcrusherBits: {
    min: 1,
    max: 8,
    step: 1,
    default: 4,
    label: 'CRUSHER BITS',
    isEffect: true,
    nodeKey: 'fxBitcrusher',
    targetParam: 'bits',
    group: 'crusher',
    supportedEngines: ALL_ENGINES,
  },

  distortionWet: {
    ...RANGE_MIX_WET,
    default: 0.35,
    label: 'DISTORTION MIX',
    isEffect: true,
    nodeKey: 'fxDistortion',
    targetParam: 'wet',
    bypassValue: 0.0,
    group: 'distortion',
    supportedEngines: ALL_ENGINES,
  },
  distortionDrive: {
    min: 0.0,
    max: 2.0,
    step: 0.1,
    default: 1.2,
    label: 'DISTORTION DRIVE',
    isEffect: true,
    nodeKey: 'fxDistortion',
    targetParam: 'distortion',
    group: 'distortion',
    supportedEngines: ALL_ENGINES,
  },

  delayWet: {
    ...RANGE_MIX_WET,
    default: 0.3,
    label: 'DELAY MIX',
    isEffect: true,
    nodeKey: 'fxDelay',
    targetParam: 'wet',
    bypassValue: 0.0,
    group: 'delay',
    supportedEngines: ALL_ENGINES,
  },
  delayFeedback: {
    min: 0.0,
    max: 0.95,
    step: 0.05,
    default: 0.4,
    label: 'DELAY FEEDBACK',
    isEffect: true,
    nodeKey: 'fxDelay',
    targetParam: 'feedback',
    group: 'delay',
    supportedEngines: ALL_ENGINES,
  },
};

export const DRUM_PRESETS = {
  kick: {
    engineType: 'membraneSynth',
    volume: -10,
    attack: 0.005,
    decay: 0.12,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  snare: {
    engineType: 'noiseSynth',
    volume: -12,
    attack: 0.005,
    decay: 0.1,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  hiHat: {
    engineType: 'metalSynth',
    volume: -12,
    attack: 0.005,
    decay: 0.05,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  hiHatClose: {
    engineType: 'metalSynth',
    volume: -12,
    attack: 0.005,
    decay: 0.04,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  hiHatOpen: {
    engineType: 'metalSynth',
    volume: -10,
    attack: 0.005,
    decay: 0.3,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  crash: {
    engineType: 'metalSynth',
    volume: -8,
    attack: 0.01,
    decay: 1.5,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  ride: {
    engineType: 'metalSynth',
    volume: -10,
    attack: 0.001,
    decay: 0.8,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
  tom: {
    engineType: 'membraneSynth',
    volume: -12,
    pitchDecay: 0.08,
    octaves: 4,
    attack: 0.005,
    decay: 0.4,
    release: 0.3,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
};

export const EFFECT_DEVICES = {
  crusher: {
    nodeKey: 'fxBitcrusher',
    ClassRef: Tone.BitCrusher,
    defaultParams: { bits: 4 },
    label: 'BITCRUSHER',
    groupKey: 'crusher',
    activeKey: 'bitcrusherActive',
  },
  distortion: {
    nodeKey: 'fxDistortion',
    ClassRef: Tone.Distortion,
    defaultParams: { distortion: 1.5, oversample: '4x' },
    label: 'DISTORTION',
    groupKey: 'distortion',
    activeKey: 'distortionActive',
  },
  filter: {
    nodeKey: 'fxFilter',
    ClassRef: Tone.Filter,
    defaultParams: { type: 'lowpass', frequency: 10000 },
    label: 'FILTER',
    groupKey: 'filter',
  },
  delay: {
    nodeKey: 'fxDelay',
    ClassRef: Tone.FeedbackDelay,
    defaultParams: { delayTime: '8n', feedback: 0.25 },
    label: 'DELAY',
    groupKey: 'delay',
    activeKey: 'delayActive',
  },
};

export const DRUM_EFFECTS_CHAIN = ['crusher', 'distortion', 'filter', 'delay'];
export const UI_EFFECTS_LIST = ['crusher', 'distortion', 'delay'];

export const SYNTH_PRESETS = {
  synth1: {
    engineType: 'monoSynth',
    oscillatorType: 'square',
    volume: -14,
    attack: 0.005,
    decay: 0.2,
    sustain: 0.3,
    release: 0.15,
    filterCutoff: 4500,
    bitcrusherWet: 0.15,
    bitcrusherBits: 4,
    distortionWet: 0.0,
    distortionDrive: 1.5,
    delayWet: 0.25,
    delayFeedback: 0.25,
    synthGlide: 0.0,
    filterQ: 1.0,
    filterEnvOctaves: 0.0,
    bitcrusherActive: true,
    distortionActive: false,
    delayActive: true,
  },
  synth2: {
    engineType: 'monoSynth',
    oscillatorType: 'triangle',
    volume: -10,
    attack: 0.005,
    decay: 0.5,
    sustain: 0.6,
    release: 0.2,
    filterCutoff: 800,
    synthGlide: 0.0,
    filterQ: 1.0,
    filterEnvOctaves: 0.0,
    bitcrusherActive: false,
    distortionActive: false,
    delayActive: false,
  },
};

export const DRUM_TYPE_MAP = {
  kick: 'MembraneSynth',
  snare: 'NoiseSynth',
  hiHat: 'MetalSynth',
  hiHatClose: 'MetalSynth',
  hiHatOpen: 'MetalSynth',
  crash: 'MetalSynth',
  ride: 'MetalSynth',
  tom: 'MembraneSynth',
};
